### ISSUE TITLE
请问能否将模型发布在torch hub上？

### ISSUE THREAD

**Issue by rener2020** [ppogg/shufflev2-yolov5#7]

**Comment by ppogg** [comment]
需要看后续的优化，如你所见，我在博客中说过这玩意如果用在gpu上性价比是十分低的：
![image](https://user-images.githubusercontent.com/82716366/130354911-898e2b77-6690-4f7b-a446-27e710835771.png)
速度并没有提升太多，精度也远比不上yolov5s，所以后续可能会针对gpu做一些优化

**Comment by rener2020** [comment]
了解了！谢谢~~

**Comment by ppogg** [comment]
不客气的朋友~
