### ISSUE TITLE
训不到大佬的结果

### ISSUE THREAD

**Issue by hyaihjq** [ppogg/shufflev2-yolov5#8]
python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 512 --data data/coco.yaml --cfg models/yolov5ss-1.0.yaml --img-size 320 --weights '' --cache-images

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.184
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.321
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.186
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.056
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.169
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.303
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.192
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.325
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.379
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.143
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.406
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.578

**Comment by ppogg** [comment]
这是我的训练时使用的命令：
python -m torch.distributed.launch --nproc_per_node 8 train.py --batch-size 64 --data data/coco.yaml --cfg models/yolov5ss-1.0.yaml --img-size 640 --weights 'weights/shufflenetv2_x1-5666bf0f80.pth' 
请不要一开始就使用320px进行训练，这是一个小模型，特征提取能力本来就很低，如果一开始直接使用320进行训练，会导致模型直接陷入到局部鞍点，另外，请在最后100个epoch将学习率调整为0.001，祝好运！

**Comment by hyaihjq** [comment]
谢谢
